using CartSync.Data.Entities;
using CartSync.Objects;

namespace CartSync.SeedData;

// ReSharper disable StringLiteralTypo
public static partial class SeedData
{
    public static List<Item> Items =>
    [
        new() { ItemId = Ulid.Parse("01KJ7FP1SWB7MC44ZKTAAQQG28"), ItemName = "Apple Cider Vinegar", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1SW7REJ08JDZBN01FXP"), ItemName = "Balsamic Vinegar", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1SW0BV4XXEQBN4290RJ"), ItemName = "Red Wine Vinegar", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1SXZ759JQQ01C7NAQGQ"), ItemName = "Rice Wine Vinegar", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1SX76EGJ62CCKMHY9XD"), ItemName = "Honey", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1SXJTXCTKNMTR04FM0P"), ItemName = "Olive Oil", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1SX7H3W4NBA3FYDM1WQ"), ItemName = "Bagels", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1SXJH6KH28XXK14YSWP"), ItemName = "Bread", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1SXGVAE8N8KM9ZN2YEN"), ItemName = "Croutons", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1SXJA7NNW4GS2RKYPD6"), ItemName = "English Muffins", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1SXRNV10J0P94YVGQJR"), ItemName = "Hamburger Buns", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1SXGFCAZGZ1PV1NVABX"), ItemName = "Canned fruit", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1SXQCSD27WD39S2FEVA"), ItemName = "Spam", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1SXPSBHKZYCD3J4CGNZ"), ItemName = "Tuna", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1SYXD38Q81HX0Y83XDP"), ItemName = "Mayonnaise", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1SY6G5S4CRFCW6PQJ0N"), ItemName = "Ranch Dressing", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1SYJ6Z8SZ3HWAAQBGWJ"), ItemName = "Natural Peanut Butter", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1SYTCT8T04WGM9SZHZK"), ItemName = "Applesauce", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1SYEM02KJ2NBQQ85XZA"), ItemName = "Barbecue Sauce", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1SYZ08KMA51NHQ82B0H"), ItemName = "Dijon Mustard", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1SYKVCXJA9S0VDMGJV5"), ItemName = "Ketchup", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1SY36X68NVDDG0R0NEV"), ItemName = "Mustard", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1SYYJ4800B9FV2SEFY4"), ItemName = "Worcestershire sauce", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1SYBX64RZWM1JERTBQM"), ItemName = "Kalamata Olives", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1SY60HK9F400HVC4N56"), ItemName = "Olives", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1SYEA004VH6WJXTR8T7"), ItemName = "Pickels", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1SY9GXPKJ4K66ZM2YG6"), ItemName = "Pizza Sauce", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1SYM273XNGKXD1MJBB2"), ItemName = "Tortillas", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1SZT9Q1A2276MHRY0VM"), ItemName = "Tortillas (Small)", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1SZFZJB6NG6RBVZN6K6"), ItemName = "Ramen", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1SZ1HKQ8N9BKFRTFK9Z"), ItemName = "Black Beans", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1SZDJ0RZGAF3KATBBRT"), ItemName = "Butter Beans", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1SZ9T9QM91V3DNDJ1SC"), ItemName = "Cannellini Beans", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1SZQCF61GBVD9W4BKCV"), ItemName = "Corn (Canned)", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1SZB31PRBHYQ7JW1EDY"), ItemName = "Green Beans", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1SZGEZKCQEC88268VGF"), ItemName = "Kidney Beans", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1SZPJ8M0HTSKPRZMSDH"), ItemName = "Crushed Tomatoes", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1SZSFXYNYPPD1WH0ZQY"), ItemName = "Diced Tomatoes", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1SZ7FKZ864PMFJKJRWH"), ItemName = "Fire Roasted Diced Tomatoes", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1SZXFBC84PKBVCKJ7T1"), ItemName = "Petite Diced Tomatoes", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1SZN8AZVVYMMGBEMQAT"), ItemName = "Tomato Paste", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1SZ8NH6G8VRJYZD9BFC"), ItemName = "Basil Pesto", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1SZP14BHZAC5MQGZJPQ"), ItemName = "Grated Parmesan", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1SZ7M74YFXR2BVYBTQD"), ItemName = "Alfredo Sauce", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1SZ5CYC7AM977XBYM1A"), ItemName = "Fettuccine Pasta", Temp = Temp.Ambient, DefaultUnitType = UnitType.WeightOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1T06NPJ17YC66Q9Z37N"), ItemName = "Boxed Mac & Cheese", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T0NK9A0NAD1PKXPR5P"), ItemName = "Macaroni Pasta", Temp = Temp.Ambient, DefaultUnitType = UnitType.WeightOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1T0RM9JJ3ABX6X063Z8"), ItemName = "Marinara Sauce", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T0HSNXDE5B85R3T2CB"), ItemName = "Penne Pasta", Temp = Temp.Ambient, DefaultUnitType = UnitType.WeightOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1T0GHMMAC6PH1PFJS88"), ItemName = "Taco Seasoning", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T0X4ZQEZWCK5ZSPGKK"), ItemName = "Chicken Broth", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T05E4VHBC3FP0VTENM"), ItemName = "Soup", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T0QJH8BHHZ4W8M5GY8"), ItemName = "Vegetable Broth", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T04JVNMS10AGP93HN5"), ItemName = "Candy", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T0PYM9A4RKZW1V5V71"), ItemName = "Lo Mein Noodles", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T0R1ZEESKMB5D683W1"), ItemName = "Oyster Sauce", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T0XYNRDV06KZ7SKW7C"), ItemName = "Rice", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T0WXDWAADQXGJY4QN0"), ItemName = "Soy Sauce", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T033NTRZR9JXQ2ZZ10"), ItemName = "Sriracha", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T0A0KS92F2CXK0599C"), ItemName = "Toasted Sesame Oil", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T0C3XQ0HBM7BM610XX"), ItemName = "Lemon Juice", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T0WHNWR26VSE6W54A0"), ItemName = "Lime Juice", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T01T4V1PSE185MK7PQ"), ItemName = "Panko", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T1NEETS6AJ3NX752ZY"), ItemName = "Diced Green Chilies", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T1M9VHW58CK1Q1VG43"), ItemName = "Salsa", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T1KQD1JDWXGY5CZVRF"), ItemName = "Basil", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T1EPHYZB92X64J0N7Y"), ItemName = "Black Pepper", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTeaspoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T1HXYZ39GA6BGHSHSF"), ItemName = "Cayenne pepper", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T1W79AM4YY2NYGQT9B"), ItemName = "Chili powder", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T1E1F50Q5109E41HNR"), ItemName = "Chipotle Powder", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T1W2M4C4H9WSPCK08E"), ItemName = "Cinnamon", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T1BGXT2N7CNKYBSNMS"), ItemName = "Cocoa Powder", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T1T8DEN0YVD1230ZGE"), ItemName = "Coriander", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T19VNWY73N5JJC7FB0"), ItemName = "Crushed Red Pepper", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T1GWNH6BKEX9P3C4MG"), ItemName = "Cumin", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T1M3V09CZQ5XHX1HR8"), ItemName = "Dill", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T18ZTVZR2RHJXQSKAF"), ItemName = "Garlic Powder", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T118BM85NJZ9BTB8WW"), ItemName = "Ground Cinnamon", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T1SRGY9YRCFB77NA5B"), ItemName = "Ground Cloves", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T2GGR25BRWM1REJGP9"), ItemName = "Ground Cumin", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T2GXAVRFMMYV872DE0"), ItemName = "Ground Ginger", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T2SR7MA73ENVK6C99M"), ItemName = "Ground Nutmeg", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T2B1GJYWEZ5KSDMD87"), ItemName = "Italian Seasoning", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T2Z1R0NX8X2QN3PSTG"), ItemName = "Lemon Pepper", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T29WYP4JPE5WC5PY3D"), ItemName = "Onion Powder", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T2TGTDZKY4S3JVY7DP"), ItemName = "Oregano", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T23EMKHVBRKMDNR2EQ"), ItemName = "Rosemary", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T28C99A5GH7D12GT62"), ItemName = "Sage", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T2G8F1TDEWA8FS9M5X"), ItemName = "Salt", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTeaspoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T2EHGYPJHME23G929H"), ItemName = "Sesame seeds", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T2TN7PYYYS3T74JXY2"), ItemName = "Smoked Paprika", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T25ZDMDVESH0KXFGR6"), ItemName = "Thyme", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T2SXAAQ6DMK73BP6AA"), ItemName = "Vanilla Extract", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T2EVETR642CBDHBCJQ"), ItemName = "Baking Powder", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T2AB11SDZEF6TEEY04"), ItemName = "Breadcrumbs", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T2ATAVJTXM2GY2M82K"), ItemName = "Brown Sugar", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T3S05ZWTB2GKPEBTSJ"), ItemName = "Chia Seeds", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T36NTEECR9BR71YVHK"), ItemName = "Cornmeal", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T3CFX9KNPGYH6AXNK0"), ItemName = "Cornstarch", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T3TQ59RHX6ZVAA8DP4"), ItemName = "Evaporated Milk", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups,},
        new() { ItemId = Ulid.Parse("01KJ7FP1T3HW7PXTDEGZ0WT5ST"), ItemName = "Flour", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T3Y9W2GXTN611E9W7A"), ItemName = "Molasses", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T3CKMB38E6C8H71KHF"), ItemName = "Powdered Sugar", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T30ESP6VCBVBSYV4WJ"), ItemName = "Semi-Sweet Chocolate", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T3HD2VEBMJ1N7FYHMW"), ItemName = "Sugar", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T36YSH4J9KZGT0AW0N"), ItemName = "Sweetened Condensed Milk", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T382PMQVESR1842Y15"), ItemName = "Yeast", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T3TMF5SNXSX7784C5D"), ItemName = "Canola Oil", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T3KP7XWCV0YJX0Q3AS"), ItemName = "Sesame Oil", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T3N50KKWYTH3B9HH4Q"), ItemName = "Vegetable Oil", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T3SX3NE2TPX1P88CST"), ItemName = "Pancakes", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T3DH5JXF6A450B73WQ"), ItemName = "Maple Syrup", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T3A2ZSQEBKRK4799VK"), ItemName = "Canned Coconut Milk", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1T41SCHTEX86E7QAZG6"), ItemName = "Pumpkin Puree", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1T49M2Q46RMG9H1CJ7N"), ItemName = "Brownie Mix", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T4N9D2F9MF817MWDKQ"), ItemName = "Mashed Potatoes", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T4NF8VBPN339CA29SH"), ItemName = "Breakfast Bars", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T4JTRK1R4G03Z1RG04"), ItemName = "Cereal", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T4XGHXJZ7QDN224T42"), ItemName = "Oatmeal", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T4D0T89PD363X85KA7"), ItemName = "Poptarts", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T4Q2RZEME6W44RC6ZZ"), ItemName = "Rolled Oats", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T4ATAQRZTQ4EH43YXF"), ItemName = "Cashews", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T4XYFF920VFH0RJ0MF"), ItemName = "Peanuts", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T4FGG4QM74NKGCTFFR"), ItemName = "Pecans", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T4G3YSBNCF0HES9X99"), ItemName = "Walnuts", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T4Y3HARG2WXDBC44VS"), ItemName = "Frozen Pizza", Temp = Temp.Frozen, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T4MNYXP8GH9B1ET134"), ItemName = "Impossible", Temp = Temp.Frozen, DefaultUnitType = UnitType.WeightOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1T46W4HE9ERA4WSVP74"), ItemName = "Frozen Broccoli", Temp = Temp.Frozen, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T4V1V8TGAV09B497ED"), ItemName = "Frozen Carrots", Temp = Temp.Frozen, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T4S8WHWBKB2CGF06JR"), ItemName = "Frozen Corn", Temp = Temp.Frozen, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T451NQRKYS520TX34V"), ItemName = "Frozen Edamame", Temp = Temp.Frozen, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T5TPBDG052BEXK0G7D"), ItemName = "Frozen Green Beans", Temp = Temp.Frozen, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T5W9VZPT976VAR47RV"), ItemName = "Frozen Onions and Peppers", Temp = Temp.Frozen, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T59DPMJDEDDYHDS150"), ItemName = "Frozen Peas", Temp = Temp.Frozen, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T5KPNSDQ0RZ0CM9KCZ"), ItemName = "Frozen Pineapple", Temp = Temp.Frozen, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T5P10CN25GN44H5WJM"), ItemName = "Frozen Raspberries", Temp = Temp.Frozen, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T50FAT0672MGE01PCF"), ItemName = "Frozen Spinach", Temp = Temp.Frozen, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T59GSFKWBM5KJTXP6K"), ItemName = "Frozen Vegetables", Temp = Temp.Frozen, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T5XFZJP9WZ4QW8W4DE"), ItemName = "Frozen Meals", Temp = Temp.Frozen, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T5KW5Y9CKSRKRZFJF8"), ItemName = "Orange Juice Concentrate", Temp = Temp.Frozen, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T5CNPQCY0CKR8P4WMW"), ItemName = "Black Bean Burgers", Temp = Temp.Frozen, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T5DGEJEVY5MWHEFXZV"), ItemName = "Chick'n Patties", Temp = Temp.Frozen, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T5FRQTGGTNG88BS2MC"), ItemName = "Ice Cream", Temp = Temp.Frozen, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T57FPG7GX7D8S0FEQ2"), ItemName = "Breakfast Burritos", Temp = Temp.Frozen, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T5NN483JW1WQ60WMAS"), ItemName = "Breakfast Sandwiches", Temp = Temp.Frozen, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T58P9BCNE11KZX48R0"), ItemName = "Hashbrowns", Temp = Temp.Frozen, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T54S9Y9QY40EAV3781"), ItemName = "Tater tots", Temp = Temp.Frozen, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T5YMHX7358RHZC6HMM"), ItemName = "Milk", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups, UncapCartUnits = true},
        new() { ItemId = Ulid.Parse("01KJ7FP1T5PESBF6Z50V7SDN21"), ItemName = "Oat Milk", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups, UncapCartUnits = true },
        new() { ItemId = Ulid.Parse("01KJ7FP1T51Y3BHRNMNC6336VR"), ItemName = "Butter", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T625FMF1R9V9SXSEKN"), ItemName = "Half & Half", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups, UncapCartUnits = true },
        new() { ItemId = Ulid.Parse("01KJ7FP1T6A3NZV6HH49BSDZG1"), ItemName = "Heavy Cream", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups, UncapCartUnits = true },
        new() { ItemId = Ulid.Parse("01KJ7FP1T6DVR9W7G4VTZKPFYQ"), ItemName = "Heavy Whipping Cream", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T63WH5NJGAC43667AM"), ItemName = "Margarine", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T64BBS53E02W0WF94G"), ItemName = "Greek Yogurt (Plain)", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T6KT3KEG953QR1Y29P"), ItemName = "Yogurt", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T6WP6DNB0BYK2S6AYH"), ItemName = "Eggs", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T66DJS4PWJGVX45KJ2"), ItemName = "Sour Cream", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T6EKSXTJPP9CZQJHYY"), ItemName = "Orange Juice", Temp = Temp.Cold, DefaultUnitType = UnitType.Count, UncapCartUnits = true },
        new() { ItemId = Ulid.Parse("01KJ7FP1T6XW7XFFW3CD0889AY"), ItemName = "Iced Coffee", Temp = Temp.Cold, DefaultUnitType = UnitType.Count, UncapCartUnits = true },
        new() { ItemId = Ulid.Parse("01KJ7FP1T6EYBNP50HHHN68RXQ"), ItemName = "Bacon", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T6DTTRF20SRA6DEFKY"), ItemName = "Chicken", Temp = Temp.Cold, DefaultUnitType = UnitType.WeightPounds },
        new() { ItemId = Ulid.Parse("01KJ7FP1T61Z48DW2G2C8FN6V9"), ItemName = "Chicken Breast", Temp = Temp.Cold, DefaultUnitType = UnitType.WeightPounds },
        new() { ItemId = Ulid.Parse("01KJ7FP1T6E880ZBT5MQG2RSDB"), ItemName = "Ground beef", Temp = Temp.Cold, DefaultUnitType = UnitType.WeightPounds },
        new() { ItemId = Ulid.Parse("01KJ7FP1T64PVP9YGQ6FD85A7W"), ItemName = "Ground Italian Sausage", Temp = Temp.Cold, DefaultUnitType = UnitType.WeightPounds },
        new() { ItemId = Ulid.Parse("01KJ7FP1T6G19X9F15DZFMA59N"), ItemName = "Ground Pork", Temp = Temp.Cold, DefaultUnitType = UnitType.WeightPounds },
        new() { ItemId = Ulid.Parse("01KJ7FP1T66AA99W0SEZ1HZKAX"), ItemName = "Ground Turkey", Temp = Temp.Cold, DefaultUnitType = UnitType.WeightPounds },
        new() { ItemId = Ulid.Parse("01KJ7FP1T684XA1SSNM8KRCNJ8"), ItemName = "Porkchops", Temp = Temp.Cold, DefaultUnitType = UnitType.WeightPounds },
        new() { ItemId = Ulid.Parse("01KJ7FP1T6XA2GHE5J2B4GJ8FQ"), ItemName = "Sausage", Temp = Temp.Cold, DefaultUnitType = UnitType.WeightPounds },
        new() { ItemId = Ulid.Parse("01KJ7FP1T6N1F1W6WCEPD60Q69"), ItemName = "Sausage (Kielbasa)", Temp = Temp.Cold, DefaultUnitType = UnitType.WeightPounds },
        new() { ItemId = Ulid.Parse("01KJ7FP1T7Y2YKSHRKQVTN3P49"), ItemName = "Frozen Fish", Temp = Temp.Frozen, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T72RJMCJNE9F57R0E4"), ItemName = "Frozen Meatballs", Temp = Temp.Frozen, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T7VH0B7CNA8JYQ1XZQ"), ItemName = "Tempeh", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T7Y1ANKP64B67TC2ZP"), ItemName = "Tofu", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T71NB997F848BDNDM7"), ItemName = "Flatbread", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T7P24RWX1X4MDC8Q0P"), ItemName = "Pita Bread", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T71VR8505GFRP7N5T4"), ItemName = "Parmesan", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T7XM32Z0HNYHMP1HXA"), ItemName = "Cream Cheese", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1T7TPESFJJN36F92GT4"), ItemName = "Feta Cheese", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T7S2NZ528H7C8GJ64P"), ItemName = "Cheddar Cheese", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T7BKACC135WZWP6790"), ItemName = "Monterey Jack Cheese", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T76SVK4VTV1VYSHTJK"), ItemName = "Mozzarella Cheese", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T7ED3E2HTYY2HAQ19F"), ItemName = "Pepper Jack Cheese", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T74YPZKYFD69B7HTTE"), ItemName = "Provolone Cheese", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T7EXAWM8MV76JMCXX0"), ItemName = "White Cheddar Cheese", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T79FDVMZQGE8X3EEF3"), ItemName = "Guacamole", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T74DEWMVVJEKBPQ4QT"), ItemName = "Rotisserie Chicken", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T70NEC388AKVYJ9QK1"), ItemName = "Hummus", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeTablespoons },
        new() { ItemId = Ulid.Parse("01KJ7FP1T8CXKDKSP6NG9JEWH7"), ItemName = "Lunch Meat", Temp = Temp.Cold, DefaultUnitType = UnitType.WeightPounds },
        new() { ItemId = Ulid.Parse("01KJ7FP1T82EJFZCQKCJ9Q8WFE"), ItemName = "Kale", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T81YMYMSGF48ARHT6D"), ItemName = "Lettuce", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T88DAYMQ091XKW2JWA"), ItemName = "Mushrooms", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeOunces },
        new() { ItemId = Ulid.Parse("01KJ7FP1T8NWRKM09N5G3REMSD"), ItemName = "Shredded Carrots", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T8KT07Y5YT3C88RQHK"), ItemName = "Spinach", Temp = Temp.Cold, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T8CKRENRA6Z2ZWS6G7"), ItemName = "Sun Dried Tomatoes", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T8W6XC2H4MW8816TZ9"), ItemName = "Apples", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T8WQFYS812RPHF0N54"), ItemName = "Avocados", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T82SM3PNK1C8DRY2B3"), ItemName = "Bananas", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T84VDFM20HNZW1WP0D"), ItemName = "Bay Leaf", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T8W26FP46KKFD4HV12"), ItemName = "Bok Choy", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T8R7JKFRV7FWQXHWB4"), ItemName = "Broccoli", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T8FM7TKWSRB154BRC9"), ItemName = "Cabbage", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T8WXDBG9EEX48S80HA"), ItemName = "Carrots", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T8PRMYVSQJFE9NV62X"), ItemName = "Celery", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T82Z75EJ907QFRV1CK"), ItemName = "Coleslaw Mix", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T89PW76JVNRTBJEP89"), ItemName = "Cucumbers", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T8RRSXRXZN604B7D8D"), ItemName = "Eggplant", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T9RRET5SMWPS2BHRJJ"), ItemName = "Garlic", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T9WZ0W1243T9V89Y0F"), ItemName = "Ginger", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T9JJN8NSGT53GY40JY"), ItemName = "Grape Tomatoes", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeCups },
        new() { ItemId = Ulid.Parse("01KJ7FP1T9G3E2NEWJX1912NKZ"), ItemName = "Green Bell Peppers", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T90DF3K93H9S16Y1FT"), ItemName = "Green Onions", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T9RDF98Q1JK4N2KG8W"), ItemName = "Jalapenos", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T93A0DVP61T50E0TD6"), ItemName = "Lemons", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T9EBJJ24ABXWK91X70"), ItemName = "Limes", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T9BY74Q82Q1GAXKR0F"), ItemName = "Poblano Peppers", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T95FW6A3Z120M0ZGHM"), ItemName = "Red Bell Pepper", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T9MCPK4K1MB5RKWH68"), ItemName = "Red Onions", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T9XRAE15TNFYY04DBT"), ItemName = "Red Potatoes", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T94G8AKBSZ4VHDPEWK"), ItemName = "Roma Tomatoes", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T9D2AFVW9TBJ0GXCQW"), ItemName = "Salad Kit", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T9E6ZBJTF513G9KG0J"), ItemName = "Tomatoes", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T93BTGC53CSMXWKH7V"), ItemName = "White Onions", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1T9B2CRCX9A616NQ449"), ItemName = "Yellow Onions", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1TAWWZ54ZJY424FGKYE"), ItemName = "Yellow Squash", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1TAKKBWGTBW1RA0S2NJ"), ItemName = "Zucchini", Temp = Temp.Cold, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1TARNYVAVK8S4AKMSW6"), ItemName = "Cinnamon Rolls", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1TAJ3931F0681QV346G"), ItemName = "French Bread", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1TACWEEEV0ZJARZM4CN"), ItemName = "Garlic Bread", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1TAKN1M5KHYJNJHF587"), ItemName = "Muffins", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1TAQ0SMV2KFADQS0KTE"), ItemName = "Rolls", Temp = Temp.Ambient, DefaultUnitType = UnitType.Count },
        new() { ItemId = Ulid.Parse("01KJ7FP1TAKJ7H0H9J7HEMW93N"), ItemName = "Olive Oil (Extra-Virgin)", Temp = Temp.Ambient, DefaultUnitType = UnitType.VolumeTablespoons }
    ];
}