// <auto-generated />
using CartSync.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CartSync._Migrations
{
    [DbContext(typeof(CartSyncContext))]
    [Migration("20260323052839_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CartSync.Models.Aisle", b =>
                {
                    b.Property<string>("AisleId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("AisleName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.HasKey("AisleId");

                    b.HasIndex("StoreId");

                    b.ToTable("Aisles");
                });

            modelBuilder.Entity("CartSync.Models.Item", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("DefaultUnitType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ItemTemp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("CartSync.Models.Joins.ItemAisle", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("StoreId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("AisleId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Bay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ItemId", "StoreId");

                    b.HasIndex("AisleId");

                    b.HasIndex("StoreId");

                    b.ToTable("ItemAisles");
                });

            modelBuilder.Entity("CartSync.Models.Joins.ItemPrep", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("PrepId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.HasKey("ItemId", "PrepId");

                    b.HasIndex("PrepId");

                    b.ToTable("ItemPreps");
                });

            modelBuilder.Entity("CartSync.Models.Joins.SelectedStore", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.HasKey("UserId");

                    b.HasIndex("StoreId");

                    b.ToTable("SelectedStores");
                });

            modelBuilder.Entity("CartSync.Models.Prep", b =>
                {
                    b.Property<string>("PrepId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("PrepName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("PrepId");

                    b.ToTable("Preps");
                });

            modelBuilder.Entity("CartSync.Models.Recipe", b =>
                {
                    b.Property<string>("RecipeId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<int>("CartAmount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("CartSync.Models.RecipeInstruction", b =>
                {
                    b.Property<string>("RecipeInstructionId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<bool>("IsImage")
                        .HasColumnType("boolean");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("RecipeInstructionContent")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("RecipeInstructionId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeInstructions");
                });

            modelBuilder.Entity("CartSync.Models.RecipeSection", b =>
                {
                    b.Property<string>("RecipeSectionId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("RecipeSectionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("RecipeSectionId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeSections");
                });

            modelBuilder.Entity("CartSync.Models.RecipeSectionEntry", b =>
                {
                    b.Property<string>("RecipeSectionEntryId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("PrepId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("RecipeSectionId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("RecipeSectionEntryId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PrepId");

                    b.HasIndex("RecipeSectionId");

                    b.ToTable("RecipeSectionEntries");
                });

            modelBuilder.Entity("CartSync.Models.Store", b =>
                {
                    b.Property<string>("StoreId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("StoreId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("CartSync.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CartSync.Models.Aisle", b =>
                {
                    b.HasOne("CartSync.Models.Store", "Store")
                        .WithMany("Aisles")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CartSync.Models.Joins.ItemAisle", b =>
                {
                    b.HasOne("CartSync.Models.Aisle", "Aisle")
                        .WithMany()
                        .HasForeignKey("AisleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSync.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSync.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aisle");

                    b.Navigation("Item");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CartSync.Models.Joins.ItemPrep", b =>
                {
                    b.HasOne("CartSync.Models.Item", "Item")
                        .WithMany("ItemPreps")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSync.Models.Prep", "Prep")
                        .WithMany("ItemPreps")
                        .HasForeignKey("PrepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Prep");
                });

            modelBuilder.Entity("CartSync.Models.Joins.SelectedStore", b =>
                {
                    b.HasOne("CartSync.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSync.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CartSync.Models.RecipeInstruction", b =>
                {
                    b.HasOne("CartSync.Models.Recipe", "Recipe")
                        .WithMany("RecipeInstructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CartSync.Models.RecipeSection", b =>
                {
                    b.HasOne("CartSync.Models.Recipe", "Recipe")
                        .WithMany("RecipeSections")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CartSync.Models.RecipeSectionEntry", b =>
                {
                    b.HasOne("CartSync.Models.Item", "Item")
                        .WithMany("RecipeSectionEntries")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSync.Models.Prep", "Prep")
                        .WithMany("RecipeSectionEntries")
                        .HasForeignKey("PrepId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CartSync.Models.RecipeSection", "RecipeSection")
                        .WithMany("RecipeSectionEntries")
                        .HasForeignKey("RecipeSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Prep");

                    b.Navigation("RecipeSection");
                });

            modelBuilder.Entity("CartSync.Models.Item", b =>
                {
                    b.Navigation("ItemPreps");

                    b.Navigation("RecipeSectionEntries");
                });

            modelBuilder.Entity("CartSync.Models.Prep", b =>
                {
                    b.Navigation("ItemPreps");

                    b.Navigation("RecipeSectionEntries");
                });

            modelBuilder.Entity("CartSync.Models.Recipe", b =>
                {
                    b.Navigation("RecipeInstructions");

                    b.Navigation("RecipeSections");
                });

            modelBuilder.Entity("CartSync.Models.RecipeSection", b =>
                {
                    b.Navigation("RecipeSectionEntries");
                });

            modelBuilder.Entity("CartSync.Models.Store", b =>
                {
                    b.Navigation("Aisles");
                });
#pragma warning restore 612, 618
        }
    }
}
