namespace CartSyncBackend.Models.Seeding;

// ReSharper disable StringLiteralTypo
public static partial class SeedData
{
    public static List<RecipeInstruction> RecipeInstructions =>
    [
        new() { RecipeId = Recipes[0].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AASPZQ21E7XJ3FW1XKS"), RecipeInstructionContent = "Start by cooking 12 oz. penne pasta according to the package directions (boil a large pot of water, add the pasta, and continue to boil until al dente). While the pasta is cooking, start the “alfredo” sauce. Mince two cloves of garlic and add them to a deep skillet or pot with 2 Tbsp butter. Sauté over medium heat for 1-2 minutes, or just until the garlic is soft and fragrant, but not brown.", SortOrder = 0, IsImage = false },
        new() { RecipeId = Recipes[0].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AASCX1CH7QBW1WZJYP6"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2017/07/Add-Milk-to-Butter-and-Garlic.jpg", SortOrder = 1, IsImage = true },
        new() { RecipeId = Recipes[0].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AASECGAM09CDB2HKG0N"), RecipeInstructionContent = "Add 2 cups of whole milk to the skillet and turn the heat down to medium-low.", SortOrder = 2, IsImage = false },
        new() { RecipeId = Recipes[0].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AASZGHEA30SZQ973T65"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2017/07/Add-Cream-Cheese-to-Lighter-Spinach-Alfredo-Sauce.jpg", SortOrder = 3, IsImage = true },
        new() { RecipeId = Recipes[0].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AASENZTTM1D81SBTKCN"), RecipeInstructionContent = "Also add 6 oz. cream cheese, cut into chunks. Heat and stir or whisk the milk and cheese until it is fully heated through and the cheese has melted into the milk. You’ll want to use a whisk once the cheese begins to melt.", SortOrder = 4, IsImage = false },
        new() { RecipeId = Recipes[0].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAT7VEHYS3RJACYSFJA"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2017/07/Add-Parmesan-to-Lighter-Spinach-Alfredo-Sauce.jpg", SortOrder = 5, IsImage = true },
        new() { RecipeId = Recipes[0].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AATR0SP521V9PXE4YEX"), RecipeInstructionContent = "Whisk 3/4 cup grated Parmesan into the milk sauce. Continue to whisk while the mixture heats, allowing it to come up to a gentle simmer. When it reaches a simmer, the sauce will thicken. Once the Parmesan has fully melted in and the sauce has thickened, turn the heat down to low to keep the sauce warm. Season the sauce with 1/4 tsp salt and a generous amount of freshly cracked pepper.", SortOrder = 6, IsImage = false },
        new() { RecipeId = Recipes[0].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAT9087PPGY0YRDFDRF"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2017/07/Fresh-Baby-Spinach-for-Lighter-Spinach-Alfredo-Pasta.jpg", SortOrder = 7, IsImage = true },
        new() { RecipeId = Recipes[0].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AATF3WZCA0962Y2HBC2"), RecipeInstructionContent = "Add the spinach: Now it’s time to add the spinach. I buy these huge bags of fresh spinach, which are the same amount as those large tubs you can buy, but it’s only $3.99 (the large tubs are usually more like $5.99). Anyway, add about 4 cups of spinach to the hot alfredo sauce…", SortOrder = 8, IsImage = false },
        new() { RecipeId = Recipes[0].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAT4F2W42VK2M9WXMX9"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2017/07/Wilted-Spinach-in-Sauce.jpg", SortOrder = 9, IsImage = true },
        new() { RecipeId = Recipes[0].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AATFYR7BNG1TMHPABM4"), RecipeInstructionContent = "And stir it in until it has wilted and limp. This should only take a few minutes.", SortOrder = 10, IsImage = false },
        new() { RecipeId = Recipes[0].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AATS36P5ZECDT5567AJ"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2017/07/Add-Cooked-Pasta-to-Lighter-Spinach-Alfredo-Sauce.jpg", SortOrder = 11, IsImage = true },
        new() { RecipeId = Recipes[0].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AATH6WB5BMTWV8KRSD0"), RecipeInstructionContent = "Add the pasta: Finally, add the cooked and drained penne pasta and stir until everything is combined and coated in the thick sauce.", SortOrder = 12, IsImage = false },
        new() { RecipeId = Recipes[0].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAT0M0JBQ4MZ51ZETEH"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2017/07/Lighter-Spinach-Alfredo-Pasta-finished.jpg", SortOrder = 13, IsImage = true },

        new() { RecipeId = Recipes[1].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAT6GWE7MD68CEJK2B0"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2021/06/1-Drained-Macaroni.jpg", SortOrder = 0, IsImage = true },
        new() { RecipeId = Recipes[1].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAT3DZ8NBM1M9P9GGWG"), RecipeInstructionContent = "Bring a large pot of water to a boil for the macaroni. Once boiling, add 1/2 lb. macaroni and continue to boil until the macaroni is tender (7-10 minutes). Drain the macaroni in a colander.", SortOrder = 1, IsImage = false },
        new() { RecipeId = Recipes[1].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAT70BBRNHYFCF5C944"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2021/06/2-Butter-and-Flour.jpg", SortOrder = 2, IsImage = true },
        new() { RecipeId = Recipes[1].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AATV8XA1PY1CP5HJZ1Y"), RecipeInstructionContent = "While the macaroni is cooking, begin the cheese sauce. Add 2 Tbsp butter and 2 Tbsp all-purpose flour to a sauce pot. Cook over medium while stirring for about 2 minutes.", SortOrder = 3, IsImage = false },
        new() { RecipeId = Recipes[1].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AATGXYZ93GD16CHN07Z"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2021/06/3-Whisk-in-Milk.jpg", SortOrder = 4, IsImage = true },
        new() { RecipeId = Recipes[1].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAT08QMYPMRSHVGZMMA"), RecipeInstructionContent = "Whisk 2 cups whole milk into the saucepot with the butter and flour. Continue to cook and whisk over medium heat until the milk comes up to a simmer, at which point it will thicken. It should thicken to the consistency of cream.", SortOrder = 5, IsImage = false },
        new() { RecipeId = Recipes[1].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AATWA9011Z865SXRZQS"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2021/06/4-Whisk-in-Cheese.jpg", SortOrder = 6, IsImage = true },
        new() { RecipeId = Recipes[1].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AATWJAE38M707G1Y2X0"), RecipeInstructionContent = "Turn off the heat and begin stirring in the 8oz. shredded Monterey Jack cheese, one handful at a time, until it is all melted into the sauce.", SortOrder = 7, IsImage = false },
        new() { RecipeId = Recipes[1].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAT7YQQCJ4EFDVAPR1N"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2021/06/5-Chiles-and-seasoning.jpg", SortOrder = 8, IsImage = true },
        new() { RecipeId = Recipes[1].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AATFX78R5MWGK2QM8FD"), RecipeInstructionContent = "Drain two 4oz. cans of diced green chiles, then add them to the cheese sauce along with ½ tsp cumin, ⅛ tsp crushed red pepper, and ¼ tsp salt. Stir to combine, then taste the sauce and adjust the seasonings to your liking if needed. The sauce should taste heavily seasoned as the flavor will dilute a bit when mixed with the pasta.", SortOrder = 9, IsImage = false },
        new() { RecipeId = Recipes[1].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AATSEWQKXGRQ6RHYJCH"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2021/06/6-Pasta-and-Sauce.jpg", SortOrder = 10, IsImage = true },
        new() { RecipeId = Recipes[1].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAT6K30GRTGR8EA1KXN"), RecipeInstructionContent = "Finally, combine the cooked and drained pasta with the green chile cheese sauce.", SortOrder = 11, IsImage = false },
        new() { RecipeId = Recipes[1].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AATYBEZT44G2SAXSMQN"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2021/06/7-Finished-Green-Chile-Mac.jpg", SortOrder = 12, IsImage = true },

        new() { RecipeId = Recipes[2].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AATA0ZWB7KYCSKQVA5R"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2022/06/1-Ingredients.jpg", SortOrder = 0, IsImage = true },
        new() { RecipeId = Recipes[2].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAT0W8V9FQ47NNCCPK1"), RecipeInstructionContent = "For this recipe, you’ll need four pitas and a cup of hummus. You’ll also need to small dice half of a cucumber and a quarter of a red onion, slice a cup of grape tomatoes into halves, chop a tablespoon of fresh parsley, crumbled two ounces of feta cheese, and slice about eight kalamata olives.", SortOrder = 1, IsImage = false },
        new() { RecipeId = Recipes[2].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AATPD418D1CDHKGMGVH"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2022/06/2-Hummus-Layer-1.jpg", SortOrder = 2, IsImage = true },
        new() { RecipeId = Recipes[2].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAVJZTS0K66FBXJ3ZS4"), RecipeInstructionContent = "Spread about a quarter cup of hummus on each pita.", SortOrder = 3, IsImage = false },
        new() { RecipeId = Recipes[2].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAVZXDK0PGNDYK40JME"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2022/06/3-Cucumber-Tomato-Onion-1.jpg", SortOrder = 4, IsImage = true },
        new() { RecipeId = Recipes[2].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAVCAD21Z009176VSR9"), RecipeInstructionContent = "Add the chopped cucumber, onion, and tomatoes to each pita, then add a pinch of salt and pepper.", SortOrder = 5, IsImage = false },
        new() { RecipeId = Recipes[2].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAVWZQF5V17VZTVWMGE"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2022/06/4-Feta-Olive-Parsley-1.jpg", SortOrder = 6, IsImage = true },
        new() { RecipeId = Recipes[2].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAVP28NYZ4X96T9G463"), RecipeInstructionContent = "Top each pita with a half-ounce of feta cheese and two kalamata olives.", SortOrder = 7, IsImage = false },
        new() { RecipeId = Recipes[2].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAVJAW4SAP73M4PQFDD"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2022/06/5-Olive-Oil-Drizzle-1.jpg", SortOrder = 8, IsImage = true },
        new() { RecipeId = Recipes[2].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAV9J3ZRBWPCDCGZ359"), RecipeInstructionContent = "Finish with a drizzle of olive oil and enjoy!", SortOrder = 9, IsImage = false },
        new() { RecipeId = Recipes[2].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAV97AYJCRTMHZ05X3A"), RecipeInstructionContent = "https://www.budgetbytes.com/wp-content/uploads/2022/06/Loaded-Hummus-Pita-close.jpg", SortOrder = 10, IsImage = true },
        new() { RecipeId = Recipes[2].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAVD0WBY6Q4QQHEF83A"), RecipeInstructionContent = "Cold, crunchy, delicious, and filling! 🙌", SortOrder = 11, IsImage = false },

        new() { RecipeId = Recipes[3].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAV48KWVV7B2WQHM3XF"), RecipeInstructionContent = "https://cdn.loveandlemons.com/wp-content/uploads/2016/07/poblano-peppers-1080x1080.jpg", SortOrder = 0, IsImage = true },
        new() { RecipeId = Recipes[3].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAV23CT9F2YRDAF8F14"), RecipeInstructionContent = "Preheat the oven to 400°F and line a baking sheet with parchment pepper.", SortOrder = 1, IsImage = false },
        new() { RecipeId = Recipes[3].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAVHN2E16WFDGDZR1F4"), RecipeInstructionContent = "Slice the peppers in half and remove the seeds and ribbing. Place on the baking sheet, drizzle with olive oil and pinches of salt and pepper, and roast cut side up for 15 minutes.", SortOrder = 2, IsImage = false },
        new() { RecipeId = Recipes[3].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAVTYDHMM3KH1P7ZDKK"), RecipeInstructionContent = "In a large skillet, heat 1 tablespoon olive oil over medium heat. Add the onion, cauliflower, red pepper, cumin, coriander, oregano, garlic, 1/2 teaspoon salt, and several grinds of black pepper. Cook until the onion is soft and the cauliflower is lightly browned, about 5 to 8 minutes.", SortOrder = 3, IsImage = false },
        new() { RecipeId = Recipes[3].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAV5D2EYFXN016FNBKY"), RecipeInstructionContent = "Remove from the heat and stir in the black beans, rice, spinach, lime juice and tomatillo salsa. Taste and adjust seasonings.", SortOrder = 4, IsImage = false },
        new() { RecipeId = Recipes[3].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAVJN8C8H5E6EM6SHNN"), RecipeInstructionContent = "Scoop the filling into the peppers and bake for 15 minutes.", SortOrder = 5, IsImage = false },
        new() { RecipeId = Recipes[3].RecipeId, RecipeInstructionId = Ulid.Parse("01KJ9R2AAV5XD2RHE3WV8DRAZX"), RecipeInstructionContent = "Serve with avocado slices, tomatillo salsa, green chile cashew cream and lime slices on the side.", SortOrder = 6, IsImage = false }
    ];
}