// <auto-generated />
using CartSync.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CartSync.Database.Migrations
{
    [DbContext(typeof(CartSyncContext))]
    [Migration("20260408091214_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CartSync.Data.Entities.Aisle", b =>
                {
                    b.Property<string>("AisleId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("AisleName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.HasKey("AisleId");

                    b.HasIndex("StoreId");

                    b.ToTable("Aisles");
                });

            modelBuilder.Entity("CartSync.Data.Entities.CartEntry", b =>
                {
                    b.Property<string>("CartEntryId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("AisleId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Amounts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsChecked")
                        .HasColumnType("boolean");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("PrepId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.HasKey("CartEntryId");

                    b.HasIndex("AisleId");

                    b.HasIndex("PrepId");

                    b.HasIndex("ItemId", "PrepId")
                        .IsUnique();

                    b.ToTable("CartEntries");
                });

            modelBuilder.Entity("CartSync.Data.Entities.CartSelectItem", b =>
                {
                    b.Property<string>("CartSelectItemId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Amounts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("PrepId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.HasKey("CartSelectItemId");

                    b.HasIndex("PrepId");

                    b.HasIndex("ItemId", "PrepId")
                        .IsUnique();

                    b.ToTable("CartSelectItems");
                });

            modelBuilder.Entity("CartSync.Data.Entities.Item", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("DefaultUnitType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Temp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("UncapCartUnits")
                        .HasColumnType("boolean");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("CartSync.Data.Entities.ItemAisle", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("StoreId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("AisleId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Bay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ItemId", "StoreId");

                    b.HasIndex("AisleId");

                    b.HasIndex("StoreId");

                    b.ToTable("ItemAisles");
                });

            modelBuilder.Entity("CartSync.Data.Entities.ItemPrep", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("PrepId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.HasKey("ItemId", "PrepId");

                    b.HasIndex("PrepId");

                    b.ToTable("ItemPreps");
                });

            modelBuilder.Entity("CartSync.Data.Entities.Prep", b =>
                {
                    b.Property<string>("PrepId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("PrepName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("PrepId");

                    b.ToTable("Preps");
                });

            modelBuilder.Entity("CartSync.Data.Entities.Recipe", b =>
                {
                    b.Property<string>("RecipeId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<int>("CartQuantity")
                        .HasColumnType("integer");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("CartSync.Data.Entities.RecipeEntry", b =>
                {
                    b.Property<string>("RecipeEntryId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("PrepId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("RecipeSectionId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.HasKey("RecipeEntryId");

                    b.HasIndex("ItemId");

                    b.HasIndex("PrepId");

                    b.HasIndex("RecipeSectionId", "ItemId", "PrepId")
                        .IsUnique();

                    b.ToTable("RecipeEntries");
                });

            modelBuilder.Entity("CartSync.Data.Entities.RecipeSection", b =>
                {
                    b.Property<string>("RecipeSectionId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("RecipeSectionName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("RecipeSectionId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeSections");
                });

            modelBuilder.Entity("CartSync.Data.Entities.RecipeStep", b =>
                {
                    b.Property<string>("RecipeStepId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<bool>("IsImage")
                        .HasColumnType("boolean");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("RecipeStepContent")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("RecipeStepId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeSteps");
                });

            modelBuilder.Entity("CartSync.Data.Entities.Store", b =>
                {
                    b.Property<string>("StoreId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("StoreId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("CartSync.Data.Entities.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<byte[]>("Hash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CartSync.Data.Entities.UserSelectedStore", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("character varying(26)");

                    b.HasKey("UserId");

                    b.HasIndex("StoreId");

                    b.ToTable("UserSelectedStores");
                });

            modelBuilder.Entity("CartSync.Data.Entities.Aisle", b =>
                {
                    b.HasOne("CartSync.Data.Entities.Store", "Store")
                        .WithMany("Aisles")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CartSync.Data.Entities.CartEntry", b =>
                {
                    b.HasOne("CartSync.Data.Entities.Aisle", "Aisle")
                        .WithMany()
                        .HasForeignKey("AisleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CartSync.Data.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSync.Data.Entities.Prep", "Prep")
                        .WithMany()
                        .HasForeignKey("PrepId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Aisle");

                    b.Navigation("Item");

                    b.Navigation("Prep");
                });

            modelBuilder.Entity("CartSync.Data.Entities.CartSelectItem", b =>
                {
                    b.HasOne("CartSync.Data.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSync.Data.Entities.Prep", "Prep")
                        .WithMany()
                        .HasForeignKey("PrepId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Item");

                    b.Navigation("Prep");
                });

            modelBuilder.Entity("CartSync.Data.Entities.ItemAisle", b =>
                {
                    b.HasOne("CartSync.Data.Entities.Aisle", "Aisle")
                        .WithMany()
                        .HasForeignKey("AisleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSync.Data.Entities.Item", "Item")
                        .WithMany("ItemAisles")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSync.Data.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aisle");

                    b.Navigation("Item");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CartSync.Data.Entities.ItemPrep", b =>
                {
                    b.HasOne("CartSync.Data.Entities.Item", "Item")
                        .WithMany("ItemPreps")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSync.Data.Entities.Prep", "Prep")
                        .WithMany("ItemPreps")
                        .HasForeignKey("PrepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Prep");
                });

            modelBuilder.Entity("CartSync.Data.Entities.RecipeEntry", b =>
                {
                    b.HasOne("CartSync.Data.Entities.Item", "Item")
                        .WithMany("RecipeSectionEntries")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSync.Data.Entities.Prep", "Prep")
                        .WithMany("RecipeSectionEntries")
                        .HasForeignKey("PrepId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CartSync.Data.Entities.RecipeSection", "RecipeSection")
                        .WithMany("Entries")
                        .HasForeignKey("RecipeSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Prep");

                    b.Navigation("RecipeSection");
                });

            modelBuilder.Entity("CartSync.Data.Entities.RecipeSection", b =>
                {
                    b.HasOne("CartSync.Data.Entities.Recipe", "Recipe")
                        .WithMany("Sections")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CartSync.Data.Entities.RecipeStep", b =>
                {
                    b.HasOne("CartSync.Data.Entities.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CartSync.Data.Entities.UserSelectedStore", b =>
                {
                    b.HasOne("CartSync.Data.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSync.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CartSync.Data.Entities.Item", b =>
                {
                    b.Navigation("ItemAisles");

                    b.Navigation("ItemPreps");

                    b.Navigation("RecipeSectionEntries");
                });

            modelBuilder.Entity("CartSync.Data.Entities.Prep", b =>
                {
                    b.Navigation("ItemPreps");

                    b.Navigation("RecipeSectionEntries");
                });

            modelBuilder.Entity("CartSync.Data.Entities.Recipe", b =>
                {
                    b.Navigation("Sections");

                    b.Navigation("Steps");
                });

            modelBuilder.Entity("CartSync.Data.Entities.RecipeSection", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("CartSync.Data.Entities.Store", b =>
                {
                    b.Navigation("Aisles");
                });
#pragma warning restore 612, 618
        }
    }
}
