// <auto-generated />
using CartSyncBackend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CartSyncBackend.Migrations
{
    [DbContext(typeof(CartSyncContext))]
    [Migration("20260225100632_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("CartSyncBackend.Database.Models.Aisle", b =>
                {
                    b.Property<string>("AisleId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("AisleName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("AisleOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("AisleId");

                    b.HasIndex("StoreId");

                    b.ToTable("Aisles");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.Item", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("CartAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultUnitType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemTemp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.ItemAisle", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("AisleId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("Bay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "StoreId");

                    b.HasIndex("AisleId");

                    b.HasIndex("StoreId");

                    b.ToTable("ItemAisles");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.ItemPrep", b =>
                {
                    b.Property<string>("ItemId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrepId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId", "PrepId");

                    b.HasIndex("PrepId");

                    b.ToTable("ItemPreps");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.Prep", b =>
                {
                    b.Property<string>("PrepId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrepName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PrepId");

                    b.ToTable("Preps");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.Recipe", b =>
                {
                    b.Property<string>("RecipeId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<int>("CartAmount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipeName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.RecipeStep", b =>
                {
                    b.Property<string>("RecipeStepId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsImage")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecipeId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("RecipeStepContent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RecipeStepOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("RecipeStepId");

                    b.HasIndex("RecipeId");

                    b.ToTable("RecipeSteps");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.Store", b =>
                {
                    b.Property<string>("StoreId")
                        .HasMaxLength(26)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("StoreId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.Aisle", b =>
                {
                    b.HasOne("CartSyncBackend.Database.Models.Store", "Store")
                        .WithMany("Aisles")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.ItemAisle", b =>
                {
                    b.HasOne("CartSyncBackend.Database.Models.Aisle", "Aisle")
                        .WithMany()
                        .HasForeignKey("AisleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSyncBackend.Database.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSyncBackend.Database.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aisle");

                    b.Navigation("Item");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.ItemPrep", b =>
                {
                    b.HasOne("CartSyncBackend.Database.Models.Item", "Item")
                        .WithMany("ItemPreps")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSyncBackend.Database.Models.Prep", "Prep")
                        .WithMany("ItemPreps")
                        .HasForeignKey("PrepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Prep");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.RecipeStep", b =>
                {
                    b.HasOne("CartSyncBackend.Database.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.Item", b =>
                {
                    b.Navigation("ItemPreps");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.Prep", b =>
                {
                    b.Navigation("ItemPreps");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.Store", b =>
                {
                    b.Navigation("Aisles");
                });
#pragma warning restore 612, 618
        }
    }
}
