// <auto-generated />
using CartSyncBackend.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CartSyncBackend.Migrations
{
    [DbContext(typeof(CartSyncContext))]
    [Migration("20260224082541_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("CartSyncBackend.Database.Models.Aisle", b =>
                {
                    b.Property<byte[]>("AisleId")
                        .HasColumnType("BLOB");

                    b.Property<string>("AisleName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("AisleOrder")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("StoreId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("AisleId");

                    b.HasIndex("StoreId");

                    b.ToTable("Aisles");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.Item", b =>
                {
                    b.Property<byte[]>("ItemId")
                        .HasColumnType("BLOB");

                    b.Property<string>("CartAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultUnitType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemTemp")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.ItemAisle", b =>
                {
                    b.Property<byte[]>("ItemId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("StoreId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("AisleId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Bay")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "StoreId");

                    b.HasIndex("AisleId");

                    b.HasIndex("StoreId");

                    b.ToTable("ItemAisles");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.Store", b =>
                {
                    b.Property<byte[]>("StoreId")
                        .HasColumnType("BLOB");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("StoreId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.Aisle", b =>
                {
                    b.HasOne("CartSyncBackend.Database.Models.Store", "Store")
                        .WithMany("Aisles")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.ItemAisle", b =>
                {
                    b.HasOne("CartSyncBackend.Database.Models.Aisle", "Aisle")
                        .WithMany()
                        .HasForeignKey("AisleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSyncBackend.Database.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CartSyncBackend.Database.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aisle");

                    b.Navigation("Item");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CartSyncBackend.Database.Models.Store", b =>
                {
                    b.Navigation("Aisles");
                });
#pragma warning restore 612, 618
        }
    }
}
