using CartSyncBackend.Database.Models;
using CartSyncBackend.Database.Objects;
using Microsoft.EntityFrameworkCore;

namespace CartSyncBackend.Database;

public class CartSyncContext(DbContextOptions<CartSyncContext> options) : DbContext(options)
{
    public DbSet<Store> Stores { get; set; }
    public DbSet<Aisle> Aisles { get; set; }
    public DbSet<Item> Items { get; set; }
    public DbSet<ItemAisle> ItemAisles { get; set; }
    
    public static string DefaultPath => Path.Join(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "CartSync.db");

    protected override void OnConfiguring(DbContextOptionsBuilder options)
        => options.UseSqlite($"Data Source={DefaultPath}");
    
    protected override void ConfigureConventions(ModelConfigurationBuilder configurationBuilder)
    {
        configurationBuilder
            .Properties<Amount>()
            .HaveConversion<AmountConverter>();
           
        configurationBuilder
            .Properties<Ulid>()
            .HaveConversion<UlidToStringConverter>()
            .HaveConversion<UlidToBytesConverter>();
    }

    public static void Seed(CartSyncContext db)
    {
        (Ulid storeUlid, string storeName)[] stores =
        [
            (Ulid.Parse("01KJ7DEC2YQFR6XDT0EPGK7Y76"), "Macey's (1700 S)"),
            (Ulid.Parse("01KJ7DGWP88JC7FREBKZAS0M96"), "WinCo (2100 S)")
        ];
        
        (Ulid aisleUlid, string aisleName)[] aisles =
        [
            (Ulid.Parse("01KJ7DRVPQP582GZ622QTSHVRH"), "Aisle 02"),
            (Ulid.Parse("01KJ7DRVPRYFRSZEDF468MAZSF"), "Aisle 02 Endcap"),
            (Ulid.Parse("01KJ7DRVPSFCBN51KNK5FYBAC5"), "Aisle 03"),
            (Ulid.Parse("01KJ7DRVPSXYCDVP1SZC5VEMFF"), "Aisle 04"),
            (Ulid.Parse("01KJ7DRVPSDQVZ5PH7NY48ECBQ"), "Aisle 05"),
            (Ulid.Parse("01KJ7DRVPS7CASP7H5E3Z2PW2E"), "Aisle 06"),
            (Ulid.Parse("01KJ7DRVPS2MCGD4E1SATBQEAE"), "Aisle 07"),
            (Ulid.Parse("01KJ7DRVPSCHXF4NAWM0NCCKP5"), "Aisle 08"),
            (Ulid.Parse("01KJ7DRVPSFPFSG20C25QB77KH"), "Aisle 09"),
            (Ulid.Parse("01KJ7DRVPSPKRMM465G72AQWF5"), "Aisle 10"),
            (Ulid.Parse("01KJ7DRVPSW2HR3FA34YFMG3SQ"), "Aisle 11"),
            (Ulid.Parse("01KJ7DRVPS7Y8RGHQQ6ZXGM9H1"), "Aisle 12"),
            (Ulid.Parse("01KJ7DRVPTG3K8ASQHRH7N3PV9"), "Aisle 13"),
            (Ulid.Parse("01KJ7DRVPTG39GK16220VWG9F4"), "Aisle 14"),
            (Ulid.Parse("01KJ7DRVPT62SQ6A428PNZTEEE"), "Aisle 15"),
            (Ulid.Parse("01KJ7DRVPTZ7N2YM1FCQ0Y9MZS"), "Back Right"),
            (Ulid.Parse("01KJ7DRVPTNW9QF4YXTM9Z0R9Y"), "Back Middle"),
            (Ulid.Parse("01KJ7DRVPTYB6D6CAE76AYX7H0"), "Meat"),
            (Ulid.Parse("01KJ7DRVPTS1DY5NXC6DH220S1"), "Frozen Meat"),
            (Ulid.Parse("01KJ7DRVPTDBSRMCCWQN5KWY8S"), "Aisle 01 Endcap"),
            (Ulid.Parse("01KJ7DRVPT4VBQGS0HN91GC2S5"), "Aisle 01"),
            (Ulid.Parse("01KJ7DRVPT86FSN79T6BJ54QTX"), "Produce"),
            (Ulid.Parse("01KJ7DRVPTQMDDC5ZKS6C2ESB6"), "Bakery"),
            (Ulid.Parse("01KJ7DRVPTBKX083VAPHMTPA19"), "Example Aisle")
        ];
        
        (Ulid itemUlid, string itemName, ItemTemp itemTemp, UnitType defaultUnits)[] items =
        [
            (Ulid.Parse("01KJ7FP1SWB7MC44ZKTAAQQG28"), "Apple Cider Vinegar", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1SW7REJ08JDZBN01FXP"), "Balsamic Vinegar", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1SW0BV4XXEQBN4290RJ"), "Red Wine Vinegar", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1SXZ759JQQ01C7NAQGQ"), "Rice Wine Vinegar", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1SX76EGJ62CCKMHY9XD"), "Honey", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1SXJTXCTKNMTR04FM0P"), "Olive Oil", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1SX7H3W4NBA3FYDM1WQ"), "Bagels", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1SXJH6KH28XXK14YSWP"), "Bread", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1SXGVAE8N8KM9ZN2YEN"), "Croutons", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1SXJA7NNW4GS2RKYPD6"), "English Muffins", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1SXRNV10J0P94YVGQJR"), "Hamburger Buns", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1SXGFCAZGZ1PV1NVABX"), "Canned fruit", ItemTemp.Ambient, UnitType.VolumeOunces),
            (Ulid.Parse("01KJ7FP1SXQCSD27WD39S2FEVA"), "Spam", ItemTemp.Ambient, UnitType.VolumeOunces),
            (Ulid.Parse("01KJ7FP1SXPSBHKZYCD3J4CGNZ"), "Tuna", ItemTemp.Ambient, UnitType.VolumeOunces),
            (Ulid.Parse("01KJ7FP1SYXD38Q81HX0Y83XDP"), "Mayonnaise", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1SY6G5S4CRFCW6PQJ0N"), "Ranch Dressing", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1SYJ6Z8SZ3HWAAQBGWJ"), "Natural Peanut Butter", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1SYTCT8T04WGM9SZHZK"), "Applesauce", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1SYEM02KJ2NBQQ85XZA"), "Barbecue Sauce", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1SYZ08KMA51NHQ82B0H"), "Dijon Mustard", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1SYKVCXJA9S0VDMGJV5"), "Ketchup", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1SY36X68NVDDG0R0NEV"), "Mustard", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1SYYJ4800B9FV2SEFY4"), "Worcestershire sauce", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1SYBX64RZWM1JERTBQM"), "Kalamata Olives", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1SY60HK9F400HVC4N56"), "Olives", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1SYEA004VH6WJXTR8T7"), "Pickels", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1SY9GXPKJ4K66ZM2YG6"), "Pizza Sauce", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1SYM273XNGKXD1MJBB2"), "Tortillas", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1SZT9Q1A2276MHRY0VM"), "Tortillas (Small)", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1SZFZJB6NG6RBVZN6K6"), "Ramen", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1SZ1HKQ8N9BKFRTFK9Z"), "Black Beans", ItemTemp.Ambient, UnitType.VolumeOunces),
            (Ulid.Parse("01KJ7FP1SZDJ0RZGAF3KATBBRT"), "Butter Beans", ItemTemp.Ambient, UnitType.VolumeOunces),
            (Ulid.Parse("01KJ7FP1SZ9T9QM91V3DNDJ1SC"), "Cannellini Beans", ItemTemp.Ambient, UnitType.VolumeOunces),
            (Ulid.Parse("01KJ7FP1SZQCF61GBVD9W4BKCV"), "Corn (Canned)", ItemTemp.Ambient, UnitType.VolumeOunces),
            (Ulid.Parse("01KJ7FP1SZB31PRBHYQ7JW1EDY"), "Green Beans", ItemTemp.Ambient, UnitType.VolumeOunces),
            (Ulid.Parse("01KJ7FP1SZGEZKCQEC88268VGF"), "Kidney Beans", ItemTemp.Ambient, UnitType.VolumeOunces),
            (Ulid.Parse("01KJ7FP1SZPJ8M0HTSKPRZMSDH"), "Crushed Tomatoes", ItemTemp.Ambient, UnitType.VolumeOunces),
            (Ulid.Parse("01KJ7FP1SZSFXYNYPPD1WH0ZQY"), "Diced Tomatoes", ItemTemp.Ambient, UnitType.VolumeOunces),
            (Ulid.Parse("01KJ7FP1SZ7FKZ864PMFJKJRWH"), "Fire Roasted Diced Tomatoes", ItemTemp.Ambient, UnitType.VolumeOunces),
            (Ulid.Parse("01KJ7FP1SZXFBC84PKBVCKJ7T1"), "Petite Diced Tomatoes", ItemTemp.Ambient, UnitType.VolumeOunces),
            (Ulid.Parse("01KJ7FP1SZN8AZVVYMMGBEMQAT"), "Tomato Paste", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1SZ8NH6G8VRJYZD9BFC"), "Basil Pesto", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1SZP14BHZAC5MQGZJPQ"), "Grated Parmesan", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1SZ7M74YFXR2BVYBTQD"), "Alfredo Sauce", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1SZ5CYC7AM977XBYM1A"), "Fettuccine Pasta", ItemTemp.Ambient, UnitType.WeightOunces),
            (Ulid.Parse("01KJ7FP1T06NPJ17YC66Q9Z37N"), "Boxed Mac & Cheese", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T0NK9A0NAD1PKXPR5P"), "Macaroni Pasta", ItemTemp.Ambient, UnitType.WeightOunces),
            (Ulid.Parse("01KJ7FP1T0RM9JJ3ABX6X063Z8"), "Marinara Sauce", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T0HSNXDE5B85R3T2CB"), "Penne Pasta", ItemTemp.Ambient, UnitType.WeightOunces),
            (Ulid.Parse("01KJ7FP1T0GHMMAC6PH1PFJS88"), "Taco Seasoning", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T0X4ZQEZWCK5ZSPGKK"), "Chicken Broth", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T05E4VHBC3FP0VTENM"), "Soup", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T0QJH8BHHZ4W8M5GY8"), "Vegetable Broth", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T04JVNMS10AGP93HN5"), "Candy", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T0PYM9A4RKZW1V5V71"), "Lo Mein Noodles", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T0R1ZEESKMB5D683W1"), "Oyster Sauce", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T0XYNRDV06KZ7SKW7C"), "Rice", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T0WXDWAADQXGJY4QN0"), "Soy Sauce", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T033NTRZR9JXQ2ZZ10"), "Sriracha", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T0A0KS92F2CXK0599C"), "Toasted Sesame Oil", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T0C3XQ0HBM7BM610XX"), "Lemon Juice", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T0WHNWR26VSE6W54A0"), "Lime Juice", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T01T4V1PSE185MK7PQ"), "Panko", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T1NEETS6AJ3NX752ZY"), "Diced Green Chilies", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T1M9VHW58CK1Q1VG43"), "Salsa", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T1KQD1JDWXGY5CZVRF"), "Basil", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T1EPHYZB92X64J0N7Y"), "Black Pepper", ItemTemp.Ambient, UnitType.VolumeTeaspoons),
            (Ulid.Parse("01KJ7FP1T1HXYZ39GA6BGHSHSF"), "Cayenne pepper", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T1W79AM4YY2NYGQT9B"), "Chili powder", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T1E1F50Q5109E41HNR"), "Chipotle Powder", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T1W2M4C4H9WSPCK08E"), "Cinnamon", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T1BGXT2N7CNKYBSNMS"), "Cocoa Powder", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T1T8DEN0YVD1230ZGE"), "Coriander", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T19VNWY73N5JJC7FB0"), "Crushed Red Pepper", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T1GWNH6BKEX9P3C4MG"), "Cumin", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T1M3V09CZQ5XHX1HR8"), "Dill", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T18ZTVZR2RHJXQSKAF"), "Garlic Powder", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T118BM85NJZ9BTB8WW"), "Ground Cinnamon", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T1SRGY9YRCFB77NA5B"), "Ground Cloves", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T2GGR25BRWM1REJGP9"), "Ground Cumin", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T2GXAVRFMMYV872DE0"), "Ground Ginger", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T2SR7MA73ENVK6C99M"), "Ground Nutmeg", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T2B1GJYWEZ5KSDMD87"), "Italian Seasoning", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T2Z1R0NX8X2QN3PSTG"), "Lemon Pepper", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T29WYP4JPE5WC5PY3D"), "Onion Powder", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T2TGTDZKY4S3JVY7DP"), "Oregano", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T23EMKHVBRKMDNR2EQ"), "Rosemary", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T28C99A5GH7D12GT62"), "Sage", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T2G8F1TDEWA8FS9M5X"), "Salt", ItemTemp.Ambient, UnitType.VolumeTeaspoons),
            (Ulid.Parse("01KJ7FP1T2EHGYPJHME23G929H"), "Sesame seeds", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T2TN7PYYYS3T74JXY2"), "Smoked Paprika", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T25ZDMDVESH0KXFGR6"), "Thyme", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T2SXAAQ6DMK73BP6AA"), "Vanilla Extract", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T2EVETR642CBDHBCJQ"), "Baking Powder", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T2AB11SDZEF6TEEY04"), "Breadcrumbs", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T2ATAVJTXM2GY2M82K"), "Brown Sugar", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T3S05ZWTB2GKPEBTSJ"), "Chia Seeds", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T36NTEECR9BR71YVHK"), "Cornmeal", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T3CFX9KNPGYH6AXNK0"), "Cornstarch", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T3TQ59RHX6ZVAA8DP4"), "Evaporated Milk", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T3HW7PXTDEGZ0WT5ST"), "Flour", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T3Y9W2GXTN611E9W7A"), "Molasses", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T3CKMB38E6C8H71KHF"), "Powdered Sugar", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T30ESP6VCBVBSYV4WJ"), "Semi-Sweet Chocolate", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T3HD2VEBMJ1N7FYHMW"), "Sugar", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T36YSH4J9KZGT0AW0N"), "Sweetened Condensed Milk", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T382PMQVESR1842Y15"), "Yeast", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T3TMF5SNXSX7784C5D"), "Canola Oil", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T3KP7XWCV0YJX0Q3AS"), "Sesame Oil", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T3N50KKWYTH3B9HH4Q"), "Vegetable Oil", ItemTemp.Ambient, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T3SX3NE2TPX1P88CST"), "Pancakes", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T3DH5JXF6A450B73WQ"), "Maple Syrup", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T3A2ZSQEBKRK4799VK"), "Canned Coconut Milk", ItemTemp.Ambient, UnitType.VolumeOunces),
            (Ulid.Parse("01KJ7FP1T41SCHTEX86E7QAZG6"), "Pumpkin Puree", ItemTemp.Ambient, UnitType.VolumeOunces),
            (Ulid.Parse("01KJ7FP1T49M2Q46RMG9H1CJ7N"), "Brownie Mix", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T4N9D2F9MF817MWDKQ"), "Mashed Potatoes", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T4NF8VBPN339CA29SH"), "Breakfast Bars", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T4JTRK1R4G03Z1RG04"), "Cereal", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T4XGHXJZ7QDN224T42"), "Oatmeal", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T4D0T89PD363X85KA7"), "Poptarts", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T4Q2RZEME6W44RC6ZZ"), "Rolled Oats", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T4ATAQRZTQ4EH43YXF"), "Cashews", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T4XYFF920VFH0RJ0MF"), "Peanuts", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T4FGG4QM74NKGCTFFR"), "Pecans", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T4G3YSBNCF0HES9X99"), "Walnuts", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T4Y3HARG2WXDBC44VS"), "Frozen Pizza", ItemTemp.Frozen, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T4MNYXP8GH9B1ET134"), "Impossible", ItemTemp.Frozen, UnitType.WeightOunces),
            (Ulid.Parse("01KJ7FP1T46W4HE9ERA4WSVP74"), "Frozen Broccoli", ItemTemp.Frozen, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T4V1V8TGAV09B497ED"), "Frozen Carrots", ItemTemp.Frozen, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T4S8WHWBKB2CGF06JR"), "Frozen Corn", ItemTemp.Frozen, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T451NQRKYS520TX34V"), "Frozen Edamame", ItemTemp.Frozen, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T5TPBDG052BEXK0G7D"), "Frozen Green Beans", ItemTemp.Frozen, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T5W9VZPT976VAR47RV"), "Frozen Onions and Peppers", ItemTemp.Frozen, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T59DPMJDEDDYHDS150"), "Frozen Peas", ItemTemp.Frozen, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T5KPNSDQ0RZ0CM9KCZ"), "Frozen Pineapple", ItemTemp.Frozen, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T5P10CN25GN44H5WJM"), "Frozen Raspberries", ItemTemp.Frozen, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T50FAT0672MGE01PCF"), "Frozen Spinach", ItemTemp.Frozen, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T59GSFKWBM5KJTXP6K"), "Frozen Vegetables", ItemTemp.Frozen, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T5XFZJP9WZ4QW8W4DE"), "Frozen Meals", ItemTemp.Frozen, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T5KW5Y9CKSRKRZFJF8"), "Orange Juice Concentrate", ItemTemp.Frozen, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T5CNPQCY0CKR8P4WMW"), "Black Bean Burgers", ItemTemp.Frozen, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T5DGEJEVY5MWHEFXZV"), "Chick'n Patties", ItemTemp.Frozen, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T5FRQTGGTNG88BS2MC"), "Ice Cream", ItemTemp.Frozen, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T57FPG7GX7D8S0FEQ2"), "Breakfast Burritos", ItemTemp.Frozen, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T5NN483JW1WQ60WMAS"), "Breakfast Sandwiches", ItemTemp.Frozen, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T58P9BCNE11KZX48R0"), "Hashbrowns", ItemTemp.Frozen, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T54S9Y9QY40EAV3781"), "Tater tots", ItemTemp.Frozen, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T5YMHX7358RHZC6HMM"), "Milk", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T5PESBF6Z50V7SDN21"), "Oat Milk", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T51Y3BHRNMNC6336VR"), "Butter", ItemTemp.Cold, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T625FMF1R9V9SXSEKN"), "Half & Half", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T6A3NZV6HH49BSDZG1"), "Heavy Cream", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T6DVR9W7G4VTZKPFYQ"), "Heavy Whipping Cream", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T63WH5NJGAC43667AM"), "Margarine", ItemTemp.Cold, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T64BBS53E02W0WF94G"), "Greek Yogurt (Plain)", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T6KT3KEG953QR1Y29P"), "Yogurt", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T6WP6DNB0BYK2S6AYH"), "Eggs", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T66DJS4PWJGVX45KJ2"), "Sour Cream", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T6EKSXTJPP9CZQJHYY"), "Orange Juice", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T6XW7XFFW3CD0889AY"), "Iced Coffee", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T6EYBNP50HHHN68RXQ"), "Bacon", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T6DTTRF20SRA6DEFKY"), "Chicken", ItemTemp.Cold, UnitType.WeightPounds),
            (Ulid.Parse("01KJ7FP1T61Z48DW2G2C8FN6V9"), "Chicken Breast", ItemTemp.Cold, UnitType.WeightPounds),
            (Ulid.Parse("01KJ7FP1T6E880ZBT5MQG2RSDB"), "Ground beef", ItemTemp.Cold, UnitType.WeightPounds),
            (Ulid.Parse("01KJ7FP1T64PVP9YGQ6FD85A7W"), "Ground Italian Sausage", ItemTemp.Cold, UnitType.WeightPounds),
            (Ulid.Parse("01KJ7FP1T6G19X9F15DZFMA59N"), "Ground Pork", ItemTemp.Cold, UnitType.WeightPounds),
            (Ulid.Parse("01KJ7FP1T66AA99W0SEZ1HZKAX"), "Ground Turkey", ItemTemp.Cold, UnitType.WeightPounds),
            (Ulid.Parse("01KJ7FP1T684XA1SSNM8KRCNJ8"), "Porkchops", ItemTemp.Cold, UnitType.WeightPounds),
            (Ulid.Parse("01KJ7FP1T6XA2GHE5J2B4GJ8FQ"), "Sausage", ItemTemp.Cold, UnitType.WeightPounds),
            (Ulid.Parse("01KJ7FP1T6N1F1W6WCEPD60Q69"), "Sausage (Kielbasa)", ItemTemp.Cold, UnitType.WeightPounds),
            (Ulid.Parse("01KJ7FP1T7Y2YKSHRKQVTN3P49"), "Frozen Fish", ItemTemp.Frozen, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T72RJMCJNE9F57R0E4"), "Frozen Meatballs", ItemTemp.Frozen, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T7VH0B7CNA8JYQ1XZQ"), "Tempeh", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T7Y1ANKP64B67TC2ZP"), "Tofu", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T71NB997F848BDNDM7"), "Flatbread", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T7P24RWX1X4MDC8Q0P"), "Pita Bread", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T71VR8505GFRP7N5T4"), "Parmesan", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T7XM32Z0HNYHMP1HXA"), "Cream Cheese", ItemTemp.Cold, UnitType.VolumeOunces),
            (Ulid.Parse("01KJ7FP1T7TPESFJJN36F92GT4"), "Feta Cheese", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T7S2NZ528H7C8GJ64P"), "Cheddar Cheese", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T7BKACC135WZWP6790"), "Monterey Jack Cheese", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T76SVK4VTV1VYSHTJK"), "Mozzarella Cheese", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T7ED3E2HTYY2HAQ19F"), "Pepper Jack Cheese", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T74YPZKYFD69B7HTTE"), "Provolone Cheese", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T7EXAWM8MV76JMCXX0"), "White Cheddar Cheese", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T79FDVMZQGE8X3EEF3"), "Guacamole", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T74DEWMVVJEKBPQ4QT"), "Rotisserie Chicken", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T70NEC388AKVYJ9QK1"), "Hummus", ItemTemp.Cold, UnitType.VolumeTablespoons),
            (Ulid.Parse("01KJ7FP1T8CXKDKSP6NG9JEWH7"), "Lunch Meat", ItemTemp.Cold, UnitType.WeightPounds),
            (Ulid.Parse("01KJ7FP1T82EJFZCQKCJ9Q8WFE"), "Kale", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T81YMYMSGF48ARHT6D"), "Lettuce", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T88DAYMQ091XKW2JWA"), "Mushrooms", ItemTemp.Cold, UnitType.VolumeOunces),
            (Ulid.Parse("01KJ7FP1T8NWRKM09N5G3REMSD"), "Shredded Carrots", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T8KT07Y5YT3C88RQHK"), "Spinach", ItemTemp.Cold, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T8CKRENRA6Z2ZWS6G7"), "Sun Dried Tomatoes", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T8W6XC2H4MW8816TZ9"), "Apples", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T8WQFYS812RPHF0N54"), "Avocados", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T82SM3PNK1C8DRY2B3"), "Bananas", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T84VDFM20HNZW1WP0D"), "Bay Leaf", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T8W26FP46KKFD4HV12"), "Bok Choy", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T8R7JKFRV7FWQXHWB4"), "Broccoli", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T8FM7TKWSRB154BRC9"), "Cabbage", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T8WXDBG9EEX48S80HA"), "Carrots", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T8PRMYVSQJFE9NV62X"), "Celery", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T82Z75EJ907QFRV1CK"), "Coleslaw Mix", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T89PW76JVNRTBJEP89"), "Cucumbers", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T8RRSXRXZN604B7D8D"), "Eggplant", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T9RRET5SMWPS2BHRJJ"), "Garlic", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T9WZ0W1243T9V89Y0F"), "Ginger", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T9JJN8NSGT53GY40JY"), "Grape Tomatoes", ItemTemp.Ambient, UnitType.VolumeCups),
            (Ulid.Parse("01KJ7FP1T9G3E2NEWJX1912NKZ"), "Green Bell Peppers", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T90DF3K93H9S16Y1FT"), "Green Onions", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T9RDF98Q1JK4N2KG8W"), "Jalapenos", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T93A0DVP61T50E0TD6"), "Lemons", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T9EBJJ24ABXWK91X70"), "Limes", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T9BY74Q82Q1GAXKR0F"), "Poblano Peppers", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T95FW6A3Z120M0ZGHM"), "Red Bell Pepper", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T9MCPK4K1MB5RKWH68"), "Red Onions", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T9XRAE15TNFYY04DBT"), "Red Potatoes", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T94G8AKBSZ4VHDPEWK"), "Roma Tomatoes", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T9D2AFVW9TBJ0GXCQW"), "Salad Kit", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T9E6ZBJTF513G9KG0J"), "Tomatoes", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T93BTGC53CSMXWKH7V"), "White Onions", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1T9B2CRCX9A616NQ449"), "Yellow Onions", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1TAWWZ54ZJY424FGKYE"), "Yellow Squash", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1TAKKBWGTBW1RA0S2NJ"), "Zucchini", ItemTemp.Cold, UnitType.Count),
            (Ulid.Parse("01KJ7FP1TARNYVAVK8S4AKMSW6"), "Cinnamon Rolls", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1TAJ3931F0681QV346G"), "French Bread", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1TACWEEEV0ZJARZM4CN"), "Garlic Bread", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1TAKN1M5KHYJNJHF587"), "Muffins", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1TAQ0SMV2KFADQS0KTE"), "Rolls", ItemTemp.Ambient, UnitType.Count),
            (Ulid.Parse("01KJ7FP1TAKJ7H0H9J7HEMW93N"), "Olive Oil (Extra-Virgin)", ItemTemp.Ambient, UnitType.VolumeTablespoons)
        ];

        (Ulid itemId, Ulid storeId, Ulid aisleId, BayType bayType)[] itemAisles =
        [
            (items[0].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.Middle),
            (items[1].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.Middle),
            (items[2].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.Middle),
            (items[3].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.Middle),
            (items[4].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.End),
            (items[5].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.End),
            (items[6].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.Start),
            (items[7].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.Start),
            (items[8].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.Start),
            (items[9].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.Start),
            (items[10].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.Start),
            (items[11].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.End),
            (items[12].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.End),
            (items[13].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.End),
            (items[14].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.Start),
            (items[15].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.Start),
            (items[16].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.Middle),
            (items[17].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.End),
            (items[18].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.End),
            (items[19].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.End),
            (items[20].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.End),
            (items[21].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.End),
            (items[22].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.End),
            (items[23].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.Middle),
            (items[24].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.Middle),
            (items[25].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.Middle),
            (items[26].itemUlid, stores[0].storeUlid, aisles[1].aisleUlid, BayType.Middle),
            (items[27].itemUlid, stores[0].storeUlid, aisles[1].aisleUlid, BayType.End),
            (items[28].itemUlid, stores[0].storeUlid, aisles[1].aisleUlid, BayType.End),
            (items[29].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Middle),
            (items[30].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Start),
            (items[31].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Start),
            (items[32].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Start),
            (items[33].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Start),
            (items[34].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Start),
            (items[35].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Start),
            (items[36].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Middle),
            (items[37].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Middle),
            (items[38].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Middle),
            (items[39].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Middle),
            (items[40].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Middle),
            (items[41].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.End),
            (items[42].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.End),
            (items[43].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Middle),
            (items[44].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Middle),
            (items[45].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Middle),
            (items[46].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Middle),
            (items[47].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Middle),
            (items[48].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Middle),
            (items[49].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Start),
            (items[50].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Middle),
            (items[51].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Start),
            (items[52].itemUlid, stores[0].storeUlid, aisles[2].aisleUlid, BayType.Start),
            (items[53].itemUlid, stores[0].storeUlid, aisles[3].aisleUlid, BayType.Start),
            (items[54].itemUlid, stores[0].storeUlid, aisles[4].aisleUlid, BayType.Middle),
            (items[55].itemUlid, stores[0].storeUlid, aisles[4].aisleUlid, BayType.Middle),
            (items[56].itemUlid, stores[0].storeUlid, aisles[4].aisleUlid, BayType.Middle),
            (items[57].itemUlid, stores[0].storeUlid, aisles[4].aisleUlid, BayType.Middle),
            (items[58].itemUlid, stores[0].storeUlid, aisles[4].aisleUlid, BayType.Middle),
            (items[59].itemUlid, stores[0].storeUlid, aisles[4].aisleUlid, BayType.Middle),
            (items[60].itemUlid, stores[0].storeUlid, aisles[4].aisleUlid, BayType.Start),
            (items[61].itemUlid, stores[0].storeUlid, aisles[4].aisleUlid, BayType.Middle),
            (items[62].itemUlid, stores[0].storeUlid, aisles[4].aisleUlid, BayType.Middle),
            (items[63].itemUlid, stores[0].storeUlid, aisles[4].aisleUlid, BayType.Start),
            (items[64].itemUlid, stores[0].storeUlid, aisles[4].aisleUlid, BayType.Start),
            (items[65].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[66].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[67].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[68].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[69].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[70].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[71].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[72].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[73].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[74].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[75].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[76].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[77].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[78].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[79].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[80].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[81].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[82].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[83].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Middle),
            (items[84].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[85].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[86].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[87].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[88].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[89].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[90].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[91].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[92].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Start),
            (items[93].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Middle),
            (items[94].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Middle),
            (items[95].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Middle),
            (items[96].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Middle),
            (items[97].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Middle),
            (items[98].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Middle),
            (items[99].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Middle),
            (items[100].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Middle),
            (items[101].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Middle),
            (items[102].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Middle),
            (items[103].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Middle),
            (items[104].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Middle),
            (items[105].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Middle),
            (items[106].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Middle),
            (items[107].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.End),
            (items[108].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.End),
            (items[109].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.End),
            (items[110].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.End),
            (items[111].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.End),
            (items[112].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Middle),
            (items[113].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Middle),
            (items[114].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Middle),
            (items[115].itemUlid, stores[0].storeUlid, aisles[5].aisleUlid, BayType.Middle),
            (items[116].itemUlid, stores[0].storeUlid, aisles[7].aisleUlid, BayType.Middle),
            (items[117].itemUlid, stores[0].storeUlid, aisles[7].aisleUlid, BayType.Middle),
            (items[118].itemUlid, stores[0].storeUlid, aisles[7].aisleUlid, BayType.Middle),
            (items[119].itemUlid, stores[0].storeUlid, aisles[7].aisleUlid, BayType.Middle),
            (items[120].itemUlid, stores[0].storeUlid, aisles[7].aisleUlid, BayType.Middle),
            (items[121].itemUlid, stores[0].storeUlid, aisles[11].aisleUlid, BayType.Middle),
            (items[122].itemUlid, stores[0].storeUlid, aisles[11].aisleUlid, BayType.Middle),
            (items[123].itemUlid, stores[0].storeUlid, aisles[11].aisleUlid, BayType.Middle),
            (items[124].itemUlid, stores[0].storeUlid, aisles[11].aisleUlid, BayType.Middle),
            (items[125].itemUlid, stores[0].storeUlid, aisles[12].aisleUlid, BayType.Start),
            (items[126].itemUlid, stores[0].storeUlid, aisles[13].aisleUlid, BayType.End),
            (items[127].itemUlid, stores[0].storeUlid, aisles[13].aisleUlid, BayType.Start),
            (items[128].itemUlid, stores[0].storeUlid, aisles[13].aisleUlid, BayType.Start),
            (items[129].itemUlid, stores[0].storeUlid, aisles[13].aisleUlid, BayType.Start),
            (items[130].itemUlid, stores[0].storeUlid, aisles[13].aisleUlid, BayType.Start),
            (items[131].itemUlid, stores[0].storeUlid, aisles[13].aisleUlid, BayType.Start),
            (items[132].itemUlid, stores[0].storeUlid, aisles[13].aisleUlid, BayType.Start),
            (items[133].itemUlid, stores[0].storeUlid, aisles[13].aisleUlid, BayType.Start),
            (items[134].itemUlid, stores[0].storeUlid, aisles[13].aisleUlid, BayType.Start),
            (items[135].itemUlid, stores[0].storeUlid, aisles[13].aisleUlid, BayType.Start),
            (items[136].itemUlid, stores[0].storeUlid, aisles[13].aisleUlid, BayType.Start),
            (items[137].itemUlid, stores[0].storeUlid, aisles[13].aisleUlid, BayType.Start),
            (items[138].itemUlid, stores[0].storeUlid, aisles[13].aisleUlid, BayType.Middle),
            (items[139].itemUlid, stores[0].storeUlid, aisles[13].aisleUlid, BayType.Middle),
            (items[140].itemUlid, stores[0].storeUlid, aisles[13].aisleUlid, BayType.End),
            (items[141].itemUlid, stores[0].storeUlid, aisles[13].aisleUlid, BayType.End),
            (items[142].itemUlid, stores[0].storeUlid, aisles[14].aisleUlid, BayType.Start),
            (items[143].itemUlid, stores[0].storeUlid, aisles[14].aisleUlid, BayType.Middle),
            (items[144].itemUlid, stores[0].storeUlid, aisles[14].aisleUlid, BayType.Middle),
            (items[145].itemUlid, stores[0].storeUlid, aisles[14].aisleUlid, BayType.Middle),
            (items[146].itemUlid, stores[0].storeUlid, aisles[14].aisleUlid, BayType.Middle),
            (items[147].itemUlid, stores[0].storeUlid, aisles[15].aisleUlid, BayType.Start),
            (items[148].itemUlid, stores[0].storeUlid, aisles[15].aisleUlid, BayType.Start),
            (items[149].itemUlid, stores[0].storeUlid, aisles[15].aisleUlid, BayType.Middle),
            (items[150].itemUlid, stores[0].storeUlid, aisles[15].aisleUlid, BayType.Start),
            (items[151].itemUlid, stores[0].storeUlid, aisles[15].aisleUlid, BayType.Start),
            (items[152].itemUlid, stores[0].storeUlid, aisles[15].aisleUlid, BayType.Start),
            (items[153].itemUlid, stores[0].storeUlid, aisles[15].aisleUlid, BayType.Middle),
            (items[154].itemUlid, stores[0].storeUlid, aisles[15].aisleUlid, BayType.End),
            (items[155].itemUlid, stores[0].storeUlid, aisles[15].aisleUlid, BayType.End),
            (items[156].itemUlid, stores[0].storeUlid, aisles[16].aisleUlid, BayType.Middle),
            (items[157].itemUlid, stores[0].storeUlid, aisles[16].aisleUlid, BayType.Start),
            (items[158].itemUlid, stores[0].storeUlid, aisles[16].aisleUlid, BayType.Middle),
            (items[159].itemUlid, stores[0].storeUlid, aisles[16].aisleUlid, BayType.End),
            (items[160].itemUlid, stores[0].storeUlid, aisles[17].aisleUlid, BayType.Middle),
            (items[161].itemUlid, stores[0].storeUlid, aisles[17].aisleUlid, BayType.Middle),
            (items[162].itemUlid, stores[0].storeUlid, aisles[17].aisleUlid, BayType.Middle),
            (items[163].itemUlid, stores[0].storeUlid, aisles[17].aisleUlid, BayType.Middle),
            (items[164].itemUlid, stores[0].storeUlid, aisles[17].aisleUlid, BayType.Middle),
            (items[165].itemUlid, stores[0].storeUlid, aisles[17].aisleUlid, BayType.Middle),
            (items[166].itemUlid, stores[0].storeUlid, aisles[17].aisleUlid, BayType.Middle),
            (items[167].itemUlid, stores[0].storeUlid, aisles[17].aisleUlid, BayType.Middle),
            (items[168].itemUlid, stores[0].storeUlid, aisles[17].aisleUlid, BayType.Middle),
            (items[169].itemUlid, stores[0].storeUlid, aisles[17].aisleUlid, BayType.Middle),
            (items[170].itemUlid, stores[0].storeUlid, aisles[18].aisleUlid, BayType.Middle),
            (items[171].itemUlid, stores[0].storeUlid, aisles[18].aisleUlid, BayType.Middle),
            (items[172].itemUlid, stores[0].storeUlid, aisles[19].aisleUlid, BayType.Middle),
            (items[173].itemUlid, stores[0].storeUlid, aisles[19].aisleUlid, BayType.Middle),
            (items[174].itemUlid, stores[0].storeUlid, aisles[20].aisleUlid, BayType.End),
            (items[175].itemUlid, stores[0].storeUlid, aisles[20].aisleUlid, BayType.End),
            (items[176].itemUlid, stores[0].storeUlid, aisles[20].aisleUlid, BayType.Start),
            (items[177].itemUlid, stores[0].storeUlid, aisles[20].aisleUlid, BayType.Middle),
            (items[178].itemUlid, stores[0].storeUlid, aisles[20].aisleUlid, BayType.Start),
            (items[179].itemUlid, stores[0].storeUlid, aisles[20].aisleUlid, BayType.Middle),
            (items[180].itemUlid, stores[0].storeUlid, aisles[20].aisleUlid, BayType.Middle),
            (items[181].itemUlid, stores[0].storeUlid, aisles[20].aisleUlid, BayType.Middle),
            (items[182].itemUlid, stores[0].storeUlid, aisles[20].aisleUlid, BayType.Middle),
            (items[183].itemUlid, stores[0].storeUlid, aisles[20].aisleUlid, BayType.Middle),
            (items[184].itemUlid, stores[0].storeUlid, aisles[20].aisleUlid, BayType.Middle),
            (items[185].itemUlid, stores[0].storeUlid, aisles[20].aisleUlid, BayType.Start),
            (items[186].itemUlid, stores[0].storeUlid, aisles[20].aisleUlid, BayType.Middle),
            (items[187].itemUlid, stores[0].storeUlid, aisles[20].aisleUlid, BayType.End),
            (items[188].itemUlid, stores[0].storeUlid, aisles[20].aisleUlid, BayType.End),
            (items[189].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[190].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[191].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[192].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[193].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[194].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[195].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[196].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[197].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[198].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[199].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[200].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[201].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[202].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[203].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[204].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[205].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[206].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[207].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[208].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[209].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[210].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[211].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[212].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[213].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[214].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[215].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[216].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[217].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[218].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[219].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[220].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[221].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[222].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[223].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[224].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[225].itemUlid, stores[0].storeUlid, aisles[21].aisleUlid, BayType.Middle),
            (items[226].itemUlid, stores[0].storeUlid, aisles[22].aisleUlid, BayType.Middle),
            (items[227].itemUlid, stores[0].storeUlid, aisles[22].aisleUlid, BayType.Middle),
            (items[228].itemUlid, stores[0].storeUlid, aisles[22].aisleUlid, BayType.Middle),
            (items[229].itemUlid, stores[0].storeUlid, aisles[22].aisleUlid, BayType.Middle),
            (items[230].itemUlid, stores[0].storeUlid, aisles[22].aisleUlid, BayType.Middle),
            (items[231].itemUlid, stores[0].storeUlid, aisles[0].aisleUlid, BayType.End),
            
            (items[0].itemUlid, stores[1].storeUlid, aisles[0].aisleUlid, BayType.Start)
        ];

        for (int i = 0; i < stores.Length; i++)
        {
            db.Stores.Add(new Store
            {
                StoreId = stores[i].storeUlid,
                StoreName = stores[i].storeName
            });
        }

        for (int i = 0; i < aisles.Length - 1; i++)
        {
            db.Aisles.Add(new Aisle
            {
                StoreId = stores[0].storeUlid,
                AisleId = aisles[i].aisleUlid,
                AisleName = aisles[i].aisleName,
                AisleOrder = i
            }); 
        }
        
        db.Aisles.Add(new Aisle
        {
            StoreId = stores[0].storeUlid,
            AisleId = aisles[^1].aisleUlid,
            AisleName = aisles[^1].aisleName,
            AisleOrder = 1
        });

        for (int i = 0; i < items.Length; i++)
        {
            db.Items.Add(new Item
            {
                ItemId = items[i].itemUlid,
                ItemName = items[i].itemName,
                ItemTemp = items[i].itemTemp,
                DefaultUnitType = items[i].defaultUnits
            });
        }

        for (int i = 0; i < itemAisles.Length; i++)
        {
            db.ItemAisles.Add(new ItemAisle
            {
                ItemId = itemAisles[i].itemId,
                AisleId = itemAisles[i].aisleId,
                StoreId = itemAisles[i].storeId,
                Bay =  itemAisles[i].bayType
            });
        }

        db.SaveChanges();
    }
}